# Generated by Django 3.2 on 2022-02-07 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qraft_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
    ]
